FROM jdk-12.0.2_10-alpine

# Set the working directory
WORKDIR /app

# Copy the JAR file to the container
COPY target/demand-tracker-crud-aws-exe.jar /app/demand-tracker-crud-aws-exe.jar

# Expose the port that the application will be running on
EXPOSE 8080

# Set the command to run the application when the container starts
CMD ["java", "-jar", "/app/demand-tracker-crud-aws-exe.jar"]